name: Ci Actions with Github

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.1.1

      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: Run linter
        run: pnpm run lint
      - name: Fix linter
        run: pnpm run lint:fix
